/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "RX_1.h"
#include "RX_1_aliases.h"
#include "TX_1.h"
#include "TX_1_aliases.h"
#include "CAN.h"
#include "I2C_Servo.h"
#include "I2C_Servo_I2C.h"
#include "I2C_Servo_PINS.h"
#include "I2C_Servo_I2C_PVT.h"
#include "I2C_Servo_PVT.h"
#include "I2C_Servo_BOOT.h"
#include "Debug.h"
#include "I2C_Spectrometer.h"
#include "I2C_Spectrometer_I2C.h"
#include "I2C_Spectrometer_PINS.h"
#include "I2C_Spectrometer_I2C_PVT.h"
#include "I2C_Spectrometer_PVT.h"
#include "I2C_Spectrometer_BOOT.h"
#include "DBG_LED.h"
#include "DBG_LED_aliases.h"
#include "ERR_LED.h"
#include "ERR_LED_aliases.h"
#include "CAN_LED.h"
#include "CAN_LED_aliases.h"
#include "CAN_isr.h"
#include "CAN_HFCLK.h"
#include "I2C_Servo_SCBCLK.h"
#include "I2C_Servo_sda.h"
#include "I2C_Servo_sda_aliases.h"
#include "I2C_Servo_scl.h"
#include "I2C_Servo_scl_aliases.h"
#include "I2C_Servo_SCB_IRQ.h"
#include "Debug_IntClock.h"
#include "I2C_Spectrometer_SCBCLK.h"
#include "I2C_Spectrometer_sda.h"
#include "I2C_Spectrometer_sda_aliases.h"
#include "I2C_Spectrometer_scl.h"
#include "I2C_Spectrometer_scl_aliases.h"
#include "I2C_Spectrometer_SCB_IRQ.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyDMA.h"
#include "CyLFClk.h"
#include "cy_em_eeprom.h"

/*[]*/

