/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "CAN_RX.h"
#include "CAN_RX_aliases.h"
#include "CAN_TX.h"
#include "CAN_TX_aliases.h"
#include "CAN.h"
#include "I2C.h"
#include "I2C_I2C.h"
#include "I2C_PINS.h"
#include "I2C_I2C_PVT.h"
#include "I2C_PVT.h"
#include "I2C_BOOT.h"
#include "Debug.h"
#include "DBG_LED.h"
#include "DBG_LED_aliases.h"
#include "ERR_LED.h"
#include "ERR_LED_aliases.h"
#include "CAN_LED.h"
#include "CAN_LED_aliases.h"
#include "ADC.h"
#include "Humidity.h"
#include "Humidity_aliases.h"
#include "Temp.h"
#include "Temp_aliases.h"
#include "Clock_1.h"
#include "Status_Reg_LIM.h"
#include "LIM1.h"
#include "LIM1_aliases.h"
#include "LIM2.h"
#include "LIM2_aliases.h"
#include "LIM3.h"
#include "LIM3_aliases.h"
#include "LIM4.h"
#include "LIM4_aliases.h"
#include "LIM5.h"
#include "LIM5_aliases.h"
#include "isr_LIM.h"
#include "CAN_isr.h"
#include "CAN_HFCLK.h"
#include "I2C_SCBCLK.h"
#include "I2C_sda.h"
#include "I2C_sda_aliases.h"
#include "I2C_scl.h"
#include "I2C_scl_aliases.h"
#include "I2C_SCB_IRQ.h"
#include "Debug_IntClock.h"
#include "ADC_IRQ.h"
#include "ADC_intClock.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyDMA.h"
#include "CyLFClk.h"
#include "cy_em_eeprom.h"

/*[]*/

